import SwiftUI
import AppleAppLabUI
#if os(iOS)
import UIKit
#elseif os(macOS)
import AppKit
#endif

/// Custom row — not in AppleAppLabUI's catalog. Documented in PROJECT_LEARNINGS.md as a
/// "list row with per-currency caption + inline edit" generalization candidate.
struct LineItemRow: View {
    @Bindable var line: LineItem
    let exchangeRate: Decimal?
    /// Coordinator (2026-09-15, DESIGN_LIQUID.md § "Sheet de captura/edición de línea"): tap
    /// no longer transforms the row in place — it opens the capture/edit sheet, owned by the
    /// parent (`PeriodView`). This closure just requests that.
    let onStartEditing: () -> Void
    let onDelete: (() -> Void)?
    /// The one direct in-place mutation left on the row itself (contextMenu's "Cambiar a
    /// MXN/USD" — everything else routes through `LineCaptureSheet` now): persists + runs
    /// `recomputeForward`, same as the sheet's save does.
    let onQuickCommit: () -> Void
    /// User's change (replaces the old per-row "Pagado" toggle): swipe-leading toggles
    /// `isActive` and must run `recomputeForward` (it affects every total), so the parent
    /// owns persistence + recompute exactly like the sheet's `onSave` does for an edit.
    let onToggleActive: () -> Void
    /// Swipe-trailing's first action: toggles `isPaid`, a purely visual flag — no recompute.
    let onTogglePaid: () -> Void

    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    /// Three distinct origin icons per Jonny (DESIGN_LIQUID.md): recurring, subscription and
    /// service are visually distinguishable at a glance, all overridden to `pencil` once the
    /// user has manually edited that line ("this came from X but has its own value here").
    private var isAutoGeneratedOrigin: Bool {
        line.origin == .recurring || line.origin == .subscription || line.origin == .loan || line.origin == .investment
    }

    /// Coordinator (2026-09-15): the row no longer shows an origin icon at all (description,
    /// amount, and the "pagado" checkmark only) — but per Sarah's rule that an icon must
    /// never be the *only* indicator of origin, that information stays available: it's folded
    /// into `accessibilityStateValue` below (VoiceOver) and still shown as plain text in the
    /// edit sheet's context (the row's own origin never needed a visual cue for sighted users
    /// beyond the description itself once the icon is gone).
    private var originLabel: String? {
        if line.isManuallyEdited, isAutoGeneratedOrigin {
            return "editado manualmente"
        }
        switch line.origin {
        case .manual: return nil
        case .recurring: return "recurrente"
        case .subscription: return line.isHomeService ? "servicio del hogar" : "suscripción"
        case .loan: return "préstamo"
        case .investment: return "inversión"
        case .carryOver: return "arrastrado del mes anterior"
        }
    }

    private var convertedCaption: String? {
        guard line.currency == .mxn, let exchangeRate, exchangeRate > 0 else { return nil }
        let usd = CurrencyConversion.toUSD(amount: line.amount, currency: .mxn, rate: exchangeRate)
        return "≈ \(usd.currencyString()) USD · TC \(exchangeRate.twoDecimalString)"
    }

    var body: some View {
        // Spacing between line cards is now the block's own `spacing: 8` (PeriodView) — this
        // row no longer adds its own vertical padding around it. There is no more in-place
        // "editing" visual state — tap opens the capture/edit sheet instead (see
        // `LineCaptureSheet`, owned by `PeriodView`).
        displayRow
    }

    /// FALLBACK from the approved plan: a `List` (the only way to get native
    /// `.swipeActions`) blocked touches to `captureRow` below it even at zero rows, confirmed
    /// in the simulator — so this row implements leading/trailing swipe itself via
    /// `DragGesture`, full-swipe-only (no partial reveal-then-tap state). Eliminar/Editar
    /// (DESIGN_LIQUID.md's 2nd trailing action, explicitly never full-swipe) stay reachable
    /// via `.contextMenu` and `accessibilityActions` instead — both already gesture-free.
    @State private var dragTranslation: CGFloat = 0
    @GestureState private var isDragging = false
    private let swipeCommitThreshold: CGFloat = 88
    /// HIG #5 (Larry): swipe-trailing's semantics stay exactly as the user decided — first
    /// action is "Marcar pagado" — but Eliminar/Editar (DESIGN_LIQUID.md's original second
    /// trailing action) needed a visible, discoverable path beyond only `.contextMenu`.
    /// Dragging trailing past this second, further threshold reveals it as a genuine second
    /// stage of the same gesture (red for Eliminar, per Larry) instead of changing what the
    /// first threshold already means.
    private let swipeSecondActionThreshold: CGFloat = 176

    private var isPastSecondTrailingThreshold: Bool { !line.isPaid && dragTranslation <= -swipeSecondActionThreshold }

    #if os(iOS)
    private func hapticImpact() {
        guard !reduceMotion else { return }
        UIImpactFeedbackGenerator(style: .light).impactOccurred()
    }
    #endif

    private var swipeGesture: some Gesture {
        DragGesture(minimumDistance: 16)
            .updating($isDragging) { _, state, _ in state = true }
            .onChanged { value in
                // Vertical drags (scrolling) must not fight this gesture.
                guard abs(value.translation.width) > abs(value.translation.height) else { return }
                dragTranslation = value.translation.width
            }
            .onEnded { value in
                let translation = value.translation.width
                let settle = { withAnimation(reduceMotion ? nil : .easeOut(duration: 0.2)) { dragTranslation = 0 } }
                // "Bloqueo de líneas pagadas" (2026-09-16): once isPaid == true, swipe-leading
                // (activar/desactivar) is a no-op, and swipe-trailing never advances past the
                // first stage — "Desmarcar pagado" is the only action left, however far the
                // user drags.
                if line.isPaid {
                    if translation <= -swipeCommitThreshold {
                        settle()
                        onTogglePaid()
                        #if os(iOS)
                        hapticImpact()
                        #endif
                    } else {
                        settle()
                    }
                } else if translation >= swipeCommitThreshold {
                    settle()
                    onToggleActive()
                    #if os(iOS)
                    hapticImpact()
                    #endif
                } else if translation <= -swipeSecondActionThreshold {
                    settle()
                    if line.origin == .manual, let onDelete {
                        onDelete()
                    } else {
                        onStartEditing()
                    }
                    #if os(iOS)
                    hapticImpact()
                    #endif
                } else if translation <= -swipeCommitThreshold {
                    settle()
                    onTogglePaid()
                    #if os(iOS)
                    hapticImpact()
                    #endif
                } else {
                    settle()
                }
            }
    }

    private var displayRow: some View {
        ZStack {
            // Background hint revealed under the row while dragging — matches the icons/tints
            // `.swipeActions` would have shown (DESIGN_LIQUID.md colors: never green/red,
            // those are reserved for the sobrante semaphore).
            HStack {
                // Bloqueada: swipe-leading (activar/desactivar) no hace nada — el hint no se
                // muestra aunque haya arrastre, para no prometer una acción que no ocurrirá.
                if !line.isPaid {
                    Label(
                        line.isActive ? "Desactivar" : "Activar",
                        systemImage: line.isActive ? "minus.circle.fill" : "arrow.uturn.backward.circle.fill"
                    )
                    .labelStyle(.iconOnly)
                    .foregroundStyle(line.isActive ? .gray : .blue)
                    .opacity(dragTranslation > 8 ? 1 : 0)
                }
                Spacer()
                if isPastSecondTrailingThreshold {
                    // Second stage of the same trailing gesture, per Larry's ruling: Eliminar
                    // (manual lines) or Editar (generated lines) — visible + red, never only
                    // reachable via contextMenu.
                    Label(
                        line.origin == .manual ? "Eliminar" : "Editar",
                        systemImage: line.origin == .manual ? "trash.fill" : "pencil"
                    )
                    .labelStyle(.iconOnly)
                    .foregroundStyle(line.origin == .manual ? .red : .blue)
                } else {
                    Label(
                        line.isPaid ? "Desmarcar pagado" : "Marcar pagado",
                        systemImage: line.isPaid ? "checkmark.circle.fill" : "circle"
                    )
                    .labelStyle(.iconOnly)
                    .foregroundStyle(.blue)
                    .opacity(dragTranslation < -8 ? 1 : 0)
                }
            }

            rowContent
                .offset(x: dragTranslation)
        }
        // DESIGN_LIQUID.md § "Bloques INCOME/EXPENSES" (Figma, updated 2026-09-15): each line
        // is now its own card — `AppBackgroundSecondary` (#2A2A2A dark / Frost-equivalent
        // light), 20pt continuous radius, 16pt padding on all sides. Supersedes the earlier
        // "no background of its own" rule from the same day (the block containing card was
        // removed entirely, so each line needs to carry its own surface now).
        .padding(16)
        // "Bloqueo de líneas pagadas" (2026-09-16): tercera excepción documentada al verde
        // (junto a SOBRANTE y la píldora "Hoy") — un tinte verde translúcido sobre el Frost de
        // la card, no un reemplazo, para que siga leyéndose como la misma familia de tarjetas.
        .background(
            ZStack {
                Color("AppBackgroundSecondary")
                if line.isPaid {
                    Color.green.opacity(0.16)
                }
            }
        )
        .clipShape(RoundedRectangle(cornerRadius: 20, style: .continuous))
        // "La tarjeta inactiva se atenúa completa" — opacity now dims the whole card
        // (background included), not just the text content.
        .opacity(line.isActive ? 1 : 0.4)
        .animation(reduceMotion ? nil : .easeOut(duration: 0.2), value: line.isActive)
        .gesture(swipeGesture)
        .accessibilityElement(children: .combine)
        .accessibilityValue(accessibilityStateValue)
        .accessibilityActions {
            // Bloqueada: el resto de acciones (Editar, Activar/Desactivar, Eliminar) refleja
            // exactamente lo que el swipe/contextMenu ya no ofrecen cuando isPaid == true —
            // solo queda desmarcar pagado, la única salida del bloqueo.
            Button(line.isPaid ? "Desmarcar pagado" : "Marcar pagado") { onTogglePaid() }
            if !line.isPaid {
                Button("Editar") { onStartEditing() }
                Button(line.isActive ? "Desactivar" : "Activar") { onToggleActive() }
                if line.origin == .manual, let onDelete {
                    Button("Eliminar", role: .destructive) { onDelete() }
                }
            }
        }
        .contextMenu {
            if line.isPaid {
                Button("Desmarcar pagado", systemImage: "checkmark.circle.fill", action: onTogglePaid)
            } else {
                Button(line.isActive ? "Desactivar" : "Activar", systemImage: line.isActive ? "minus.circle.fill" : "arrow.uturn.backward.circle.fill", action: onToggleActive)
                Button("Marcar pagado", systemImage: "circle", action: onTogglePaid)
                Button(line.currency == .usd ? "Cambiar a MXN" : "Cambiar a USD") {
                    let newCurrency: Currency = line.currency == .usd ? .mxn : .usd
                    line.currency = newCurrency
                    line.isManuallyEdited = line.origin != .manual ? true : line.isManuallyEdited
                    onQuickCommit()
                    #if os(iOS)
                    UIAccessibility.post(notification: .announcement, argument: "Moneda cambiada a \(newCurrency == .usd ? "USD" : "MXN")")
                    #endif
                }
                Button("Editar", systemImage: "pencil", action: onStartEditing)
                if line.origin == .manual, let onDelete {
                    Button("Eliminar", systemImage: "trash", role: .destructive, action: onDelete)
                        #if os(macOS)
                        .keyboardShortcut(.delete, modifiers: [.command, .shift])
                        #endif
                }
            }
        }
    }

    private var rowContent: some View {
        HStack(spacing: 10) {
            VStack(alignment: .leading, spacing: 2) {
                Text(line.title)
                    .font(.body)
                if let convertedCaption {
                    Text(convertedCaption)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                        .monospacedDigit()
                }
            }

            Spacer()

            Text(line.amount.currencyString(currency: line.currency))
                .font(.body.weight(.semibold))
                .monospacedDigit()
                .strikethrough(!line.isActive)

            // DESIGN_LIQUID.md: "palomita discreta (checkmark.circle.fill, 14pt, tinte .blue)
            // a la derecha del monto — no afecta números, no cambia opacidad de nada más en
            // la fila" (its own opacity still follows the row when isActive == false, per the
            // "inactiva y pagada" combined state — it's not drawn separately at full opacity).
            if line.isPaid {
                Image(systemName: "checkmark.circle.fill")
                    .font(.system(size: 14))
                    .foregroundStyle(.blue)
                    .accessibilityHidden(true)
            }
        }
        // Coordinator (2026-09-16): plain tap no longer opens the capture/edit sheet — the
        // only way in is long-press → `.contextMenu` → "Editar" (still wired to
        // `onStartEditing()` there). Swipes (activar/desactivar, pagado, Eliminar) are
        // untouched — this was the row's own tap gesture only.
    }

    /// DESIGN_LIQUID.md: "inactiva" / "pagada" / "inactiva, pagada" / nothing — always in this
    /// order, never conveyed by color/icon alone. `originLabel` now leads the value (the row
    /// dropped its origin icon per the coordinator, so this is the only place that
    /// information still reaches VoiceOver).
    private var accessibilityStateValue: String {
        var parts: [String] = []
        if let originLabel { parts.append(originLabel) }
        if !line.isActive { parts.append("inactiva") }
        if line.isPaid { parts.append("pagada") }
        return parts.joined(separator: ", ")
    }

}
