import SwiftUI
import AppleAppLabUI
#if os(iOS)
import UIKit
#elseif os(macOS)
import AppKit
#endif

/// Custom row — not in AppleAppLabUI's catalog. Documented in PROJECT_LEARNINGS.md as a
/// "list row with per-currency caption + inline edit" generalization candidate.
struct LineItemRow: View {
    @Bindable var line: LineItem
    let exchangeRate: Decimal?
    let isEditing: Bool
    /// True while this row is a freshly-created draft from "Agregar ingreso/gasto" that
    /// hasn't been confirmed yet — gates the empty-line validation and shows "Cancelar".
    let isDraft: Bool
    let onStartEditing: () -> Void
    let onCommit: () -> Void
    let onDelete: (() -> Void)?
    /// Only used while `isDraft` — discards the draft line entirely (Bertrand's ghost-row fix).
    let onDiscardDraft: (() -> Void)?
    /// User's change (replaces the old per-row "Pagado" toggle): swipe-leading toggles
    /// `isActive` and must run `recomputeForward` (it affects every total), so the parent
    /// owns persistence + recompute exactly like `onCommit` does for an inline edit.
    let onToggleActive: () -> Void
    /// Swipe-trailing's first action: toggles `isPaid`, a purely visual flag — no recompute.
    let onTogglePaid: () -> Void

    @State private var amountText: String = ""
    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    /// A draft with an empty description or a non-positive amount must not be saveable —
    /// this is exactly the ghost-line bug Bertrand reproduced.
    private var isValidForSave: Bool {
        PeriodCoordinator.isValidManualLine(title: line.title, amount: line.amount)
    }

    /// Three distinct origin icons per Jonny (DESIGN_LIQUID.md): recurring, subscription and
    /// service are visually distinguishable at a glance, all overridden to `pencil` once the
    /// user has manually edited that line ("this came from X but has its own value here").
    private var isAutoGeneratedOrigin: Bool {
        line.origin == .recurring || line.origin == .subscription || line.origin == .loan || line.origin == .investment
    }

    private var originIcon: String? {
        if line.isManuallyEdited, isAutoGeneratedOrigin {
            return "pencil"
        }
        switch line.origin {
        case .manual: return nil
        case .recurring: return "arrow.triangle.2.circlepath"
        case .subscription: return line.isHomeService ? "house.fill" : "repeat"
        case .loan: return "banknote"
        case .investment: return "chart.line.uptrend.xyaxis"
        case .carryOver: return "arrow.turn.down.right"
        }
    }

    /// A11Y_AUDIT #3: the origin icon is the only visual signal that a line is
    /// auto-generated — VoiceOver must announce it, not silently skip it.
    private var originLabel: String? {
        if line.isManuallyEdited, isAutoGeneratedOrigin {
            return "editado manualmente"
        }
        switch line.origin {
        case .manual: return nil
        case .recurring: return "recurrente"
        case .subscription: return line.isHomeService ? "servicio del hogar" : "suscripción"
        case .loan: return "préstamo"
        case .investment: return "inversión"
        case .carryOver: return "arrastrado del mes anterior"
        }
    }

    private var isTitleEditable: Bool {
        line.origin != .carryOver
    }

    private var carryOverEditHint: String? {
        line.origin == .carryOver ? "No se puede editar porque es arrastrado del mes anterior" : nil
    }

    private var convertedCaption: String? {
        guard line.currency == .mxn, let exchangeRate, exchangeRate > 0 else { return nil }
        let usd = CurrencyConversion.toUSD(amount: line.amount, currency: .mxn, rate: exchangeRate)
        return "≈ \(usd.currencyString()) USD · TC \(exchangeRate.twoDecimalString)"
    }

    var body: some View {
        Group {
            if isEditing {
                editingRow
            } else {
                displayRow
            }
        }
        .padding(.vertical, 6)
    }

    /// FALLBACK from the approved plan: a `List` (the only way to get native
    /// `.swipeActions`) blocked touches to `captureRow` below it even at zero rows, confirmed
    /// in the simulator — so this row implements leading/trailing swipe itself via
    /// `DragGesture`, full-swipe-only (no partial reveal-then-tap state). Eliminar/Editar
    /// (DESIGN_LIQUID.md's 2nd trailing action, explicitly never full-swipe) stay reachable
    /// via `.contextMenu` and `accessibilityActions` instead — both already gesture-free.
    @State private var dragTranslation: CGFloat = 0
    @GestureState private var isDragging = false
    private let swipeCommitThreshold: CGFloat = 88

    private var swipeGesture: some Gesture {
        DragGesture(minimumDistance: 16)
            .updating($isDragging) { _, state, _ in state = true }
            .onChanged { value in
                // Vertical drags (scrolling) must not fight this gesture.
                guard abs(value.translation.width) > abs(value.translation.height) else { return }
                dragTranslation = value.translation.width
            }
            .onEnded { value in
                let translation = value.translation.width
                let settle = { withAnimation(reduceMotion ? nil : .easeOut(duration: 0.2)) { dragTranslation = 0 } }
                if translation >= swipeCommitThreshold {
                    settle()
                    onToggleActive()
                } else if translation <= -swipeCommitThreshold {
                    settle()
                    onTogglePaid()
                } else {
                    settle()
                }
            }
    }

    private var displayRow: some View {
        ZStack {
            // Background hint revealed under the row while dragging — matches the icons/tints
            // `.swipeActions` would have shown (DESIGN_LIQUID.md colors: never green/red,
            // those are reserved for the sobrante semaphore).
            HStack {
                Label(
                    line.isActive ? "Desactivar" : "Activar",
                    systemImage: line.isActive ? "minus.circle.fill" : "arrow.uturn.backward.circle.fill"
                )
                .labelStyle(.iconOnly)
                .foregroundStyle(line.isActive ? .gray : .blue)
                .opacity(dragTranslation > 8 ? 1 : 0)
                Spacer()
                Label(
                    line.isPaid ? "Desmarcar pagado" : "Marcar pagado",
                    systemImage: line.isPaid ? "checkmark.circle.fill" : "circle"
                )
                .labelStyle(.iconOnly)
                .foregroundStyle(.blue)
                .opacity(dragTranslation < -8 ? 1 : 0)
            }
            .padding(.horizontal, 12)

            rowContent
                .background(Color("AppBackground"))
                .offset(x: dragTranslation)
        }
        .clipped()
        .gesture(swipeGesture)
        .accessibilityElement(children: .combine)
        .accessibilityValue(accessibilityStateValue)
        .accessibilityActions {
            Button("Editar") { onStartEditing() }
            Button(line.isActive ? "Desactivar" : "Activar") { onToggleActive() }
            Button(line.isPaid ? "Desmarcar pagado" : "Marcar pagado") { onTogglePaid() }
            if line.origin == .manual, let onDelete {
                Button("Eliminar", role: .destructive) { onDelete() }
            }
        }
        .contextMenu {
            Button(line.isActive ? "Desactivar" : "Activar", systemImage: line.isActive ? "minus.circle.fill" : "arrow.uturn.backward.circle.fill", action: onToggleActive)
            Button(line.isPaid ? "Desmarcar pagado" : "Marcar pagado", systemImage: line.isPaid ? "checkmark.circle.fill" : "circle", action: onTogglePaid)
            Button(line.currency == .usd ? "Cambiar a MXN" : "Cambiar a USD") {
                let newCurrency: Currency = line.currency == .usd ? .mxn : .usd
                line.currency = newCurrency
                line.isManuallyEdited = line.origin != .manual ? true : line.isManuallyEdited
                onCommit()
                #if os(iOS)
                UIAccessibility.post(notification: .announcement, argument: "Moneda cambiada a \(newCurrency == .usd ? "USD" : "MXN")")
                #endif
            }
            Button("Editar", systemImage: "pencil", action: onStartEditing)
            if line.origin == .manual, let onDelete {
                Button("Eliminar", systemImage: "trash", role: .destructive, action: onDelete)
                    #if os(macOS)
                    .keyboardShortcut(.delete, modifiers: [.command, .shift])
                    #endif
            }
        }
    }

    private var rowContent: some View {
        HStack(spacing: 10) {
            if let originIcon {
                // HIG #3: scale with Dynamic Type instead of a fixed 12pt.
                Image(systemName: originIcon)
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .accessibilityLabel(originLabel ?? "")
                    .accessibilityHidden(originLabel == nil)
            }

            VStack(alignment: .leading, spacing: 2) {
                Text(line.title)
                    .font(.body)
                if let convertedCaption {
                    Text(convertedCaption)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                        .monospacedDigit()
                }
            }

            Spacer()

            Text(line.amount.currencyString(currency: line.currency))
                .font(.body.weight(.semibold))
                .monospacedDigit()
                .strikethrough(!line.isActive)

            // DESIGN_LIQUID.md: "palomita discreta (checkmark.circle.fill, 14pt, tinte .blue)
            // a la derecha del monto — no afecta números, no cambia opacidad de nada más en
            // la fila" (its own opacity still follows the row when isActive == false, per the
            // "inactiva y pagada" combined state — it's not drawn separately at full opacity).
            if line.isPaid {
                Image(systemName: "checkmark.circle.fill")
                    .font(.system(size: 14))
                    .foregroundStyle(.blue)
                    .accessibilityHidden(true)
            }
        }
        .opacity(line.isActive ? 1 : 0.4)
        .animation(reduceMotion ? nil : .easeOut(duration: 0.2), value: line.isActive)
        .contentShape(Rectangle())
        .onTapGesture {
            // While a swipe is mid-drag/revealed, a tap should dismiss it, not open edit.
            guard dragTranslation == 0 else { return }
            onStartEditing()
        }
    }

    /// DESIGN_LIQUID.md: "inactiva" / "pagada" / "inactiva, pagada" / nothing — always in this
    /// order, never conveyed by color/icon alone.
    private var accessibilityStateValue: String {
        var parts: [String] = []
        if !line.isActive { parts.append("inactiva") }
        if line.isPaid { parts.append("pagada") }
        return parts.joined(separator: ", ")
    }

    private var editingRow: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack(spacing: 8) {
                if isTitleEditable {
                    TextField("Descripción", text: $line.title)
                        .textFieldStyle(.roundedBorder)
                } else {
                    Text(line.title)
                        .foregroundStyle(.secondary)
                }
            }
            HStack(spacing: 8) {
                // Starts blank (placeholder "0.00") instead of pre-filled with "0" — a
                // pre-filled numeric TextField concatenates on the first keystroke instead
                // of replacing (typing "5" after "0.00" produced "0.005000").
                TextField("0.00", text: $amountText)
                    #if os(iOS)
                    .keyboardType(.decimalPad)
                    #endif
                    .textFieldStyle(.roundedBorder)
                    .disabled(line.origin == .carryOver)
                    .accessibilityHint(carryOverEditHint ?? "")
                    .onAppear {
                        amountText = line.amount == 0 ? "" : line.amount.twoDecimalString
                    }
                    .onChange(of: amountText) { _, newValue in
                        line.amount = Decimal(string: newValue, locale: Locale(identifier: "en_US_POSIX")) ?? 0
                    }

                Picker("Moneda", selection: $line.currency) {
                    Text("USD").tag(Currency.usd)
                    Text("MXN").tag(Currency.mxn)
                }
                .pickerStyle(.segmented)
                .frame(width: 140)
                .disabled(line.origin == .carryOver)
                .accessibilityHint(line.origin == .carryOver ? "No se puede cambiar porque es arrastrado del mes anterior" : "")

                if isDraft {
                    Button("Cancelar") {
                        onDiscardDraft?()
                    }
                    .buttonStyle(.bordered)
                }

                Button("Listo") {
                    if isDraft {
                        guard isValidForSave else { return }
                        onCommit()
                    } else {
                        if line.origin != .manual { line.isManuallyEdited = true }
                        onCommit()
                    }
                }
                .buttonStyle(.borderedProminent)
                .disabled(isDraft && !isValidForSave)
            }
            if isDraft && !isValidForSave {
                Text("Escribe una descripción y un monto mayor a 0.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
        }
        .padding(10)
        .background(
            RoundedRectangle(cornerRadius: 12, style: .continuous)
                .fill(Color("AppBackgroundSecondary"))
        )
    }
}
