import SwiftUI
import AppleAppLabUI
#if os(iOS)
import UIKit
#elseif os(macOS)
import AppKit
#endif

/// Custom row — not in AppleAppLabUI's catalog. Documented in PROJECT_LEARNINGS.md as a
/// "list row with per-currency caption + inline edit" generalization candidate.
struct LineItemRow: View {
    @Bindable var line: LineItem
    let exchangeRate: Decimal?
    /// Coordinator (2026-09-15, DESIGN_LIQUID.md § "Sheet de captura/edición de línea"): tap
    /// no longer transforms the row in place — it opens the capture/edit sheet, owned by the
    /// parent (`PeriodView`). This closure just requests that.
    let onStartEditing: () -> Void
    let onDelete: (() -> Void)?
    /// The one direct in-place mutation left on the row itself (contextMenu's "Cambiar a
    /// MXN/USD" — everything else routes through `LineCaptureSheet` now): persists + runs
    /// `recomputeForward`, same as the sheet's save does.
    let onQuickCommit: () -> Void
    /// User's change (replaces the old per-row "Pagado" toggle): swipe-leading toggles
    /// `isActive` and must run `recomputeForward` (it affects every total), so the parent
    /// owns persistence + recompute exactly like the sheet's `onSave` does for an edit.
    let onToggleActive: () -> Void
    /// Swipe-trailing's first action: toggles `isPaid`, a purely visual flag — no recompute.
    let onTogglePaid: () -> Void

    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    /// Three distinct origin icons per Jonny (DESIGN_LIQUID.md): recurring, subscription and
    /// service are visually distinguishable at a glance, all overridden to `pencil` once the
    /// user has manually edited that line ("this came from X but has its own value here").
    private var isAutoGeneratedOrigin: Bool {
        line.origin == .recurring || line.origin == .subscription || line.origin == .loan || line.origin == .investment || line.origin == .creditCard
    }

    /// Coordinator (2026-09-15): the row no longer shows an origin icon at all (description,
    /// amount, and the "pagado" checkmark only) — but per Sarah's rule that an icon must
    /// never be the *only* indicator of origin, that information stays available: it's folded
    /// into `accessibilityStateValue` below (VoiceOver) and still shown as plain text in the
    /// edit sheet's context (the row's own origin never needed a visual cue for sighted users
    /// beyond the description itself once the icon is gone).
    private var originLabel: String? {
        if line.isManuallyEdited, isAutoGeneratedOrigin {
            return String(localized: "line_origin_manually_edited", defaultValue: "manually edited")
        }
        switch line.origin {
        case .manual: return nil
        case .recurring: return String(localized: "line_origin_recurring", defaultValue: "recurring")
        case .subscription: return line.isHomeService
            ? String(localized: "line_origin_home_service", defaultValue: "home service")
            : String(localized: "line_origin_subscription", defaultValue: "subscription")
        case .loan: return String(localized: "line_origin_loan", defaultValue: "loan")
        case .investment: return String(localized: "line_origin_investment", defaultValue: "investment")
        case .carryOver: return String(localized: "line_origin_carry_over", defaultValue: "carried over from last period")
        case .creditCard: return String(localized: "line_origin_credit_card", defaultValue: "credit card")
        case .essential: return String(localized: "line_origin_essential", defaultValue: "essential")
        }
    }

    // L10N_AUDIT.md § 1 — shared action labels, [compartida] in the audit table: reused across
    // `.contextMenu`, `accessibilityActions`, and the swipe-reveal hint `Label`s below, so
    // each key/value is defined exactly once.
    private var editLabel: String { String(localized: "line_a11y_action_edit", defaultValue: "Edit") }
    private var activateLabel: String { String(localized: "line_a11y_action_activate", defaultValue: "Activate") }
    private var deactivateLabel: String { String(localized: "line_a11y_action_deactivate", defaultValue: "Deactivate") }
    private var deleteLabel: String { String(localized: "line_a11y_action_delete", defaultValue: "Delete") }
    private var markPaidLabel: String { String(localized: "line_a11y_action_mark_paid", defaultValue: "Mark as paid") }
    private var markUnpaidLabel: String { String(localized: "line_a11y_action_mark_unpaid", defaultValue: "Mark as unpaid") }

    /// Coordinator (2026-09-16): the swipe-trailing "marcar/desmarcar pagado" hint's icon
    /// tint — same source hex as the paid-card tint (`#006338`, dark green), not system blue
    /// or the default `.green`.
    private static let paidHintColor = Color(red: 0x00 / 255.0, green: 0x63 / 255.0, blue: 0x38 / 255.0)

    /// Coordinator (2026-09-21, /update-ui on node 12:7 "income card"): a fresh Figma pull shows
    /// paid rows are a SOLID `Semantic/Success Green` fill (#006338), not a translucent/dark-tint
    /// overlay — superseding the previous pass's `#14332B` tint (that was this token's "-Dark"
    /// step, meant for the row's TEXT color instead, see `paidRowTextColor` below).
    private static let paidRowBackground = Color(red: 0x00 / 255.0, green: 0x63 / 255.0, blue: 0x38 / 255.0)

    /// Coordinator (2026-09-21, /update-ui): paid rows use `Semantic/Success Green-Dark`
    /// (#14332B) for their text (title + amount), giving a subtle dark-on-green contrast instead
    /// of plain white — confirmed on both the resting and swiped-open paid row states in Figma.
    private static let paidRowTextColor = Color(red: 0x14 / 255.0, green: 0x33 / 255.0, blue: 0x2B / 255.0)

    /// Coordinator (2026-09-21, tokens update): danger red moved from system `.red` (#FF3B30) to
    /// the Figma token's `Semantic/Danger Red` (#DB281E) — darker/more muted, matching the same
    /// pass that already updated `paidHintColor`'s green.
    private static let dangerColor = Color(red: 0xDB / 255.0, green: 0x28 / 255.0, blue: 0x1E / 255.0)

    private var convertedCaption: String? {
        guard line.currency == .mxn, let exchangeRate, exchangeRate > 0 else { return nil }
        let usd = CurrencyConversion.toUSD(amount: line.amount, currency: .mxn, rate: exchangeRate)
        return String(localized: "line_converted_caption", defaultValue: "≈ \(usd.currencyString()) USD · Rate \(exchangeRate.twoDecimalString)")
    }

    var body: some View {
        // Spacing between line cards is now the block's own `spacing: 8` (PeriodView) — this
        // row no longer adds its own vertical padding around it. There is no more in-place
        // "editing" visual state — tap opens the capture/edit sheet instead (see
        // `LineCaptureSheet`, owned by `PeriodView`).
        displayRow
    }

    /// FALLBACK from the approved plan: a `List` (the only way to get native
    /// `.swipeActions`) blocked touches to `captureRow` below it even at zero rows, confirmed
    /// in the simulator — so this row implements leading/trailing swipe itself via
    /// `DragGesture`, full-swipe-only (no partial reveal-then-tap state). Eliminar/Editar
    /// (DESIGN_LIQUID.md's 2nd trailing action, explicitly never full-swipe) stay reachable
    /// via `.contextMenu` and `accessibilityActions` instead — both already gesture-free.
    @State private var dragTranslation: CGFloat = 0
    @GestureState private var isDragging = false
    private let swipeCommitThreshold: CGFloat = 88

    /// Coordinator (2026-09-21, user's explicit request): swipe-trailing is now single-stage —
    /// only "Marcar/Desmarcar pagado", full stop. The old second-stage deep-swipe (Eliminar for
    /// manual lines, Editar for generated ones) is gone; editing is press-and-hold →
    /// `.contextMenu` → "Editar" only, never a swipe gesture, so there's exactly one way in.
    private enum TrailingStage: Equatable {
        case paidToggle
    }
    @State private var committedTrailingStage: TrailingStage?

    private var currentTrailingStage: TrailingStage? {
        if let committedTrailingStage { return committedTrailingStage }
        guard dragTranslation < 0 else { return nil }
        return .paidToggle
    }

    private var settleAnimation: Animation? { reduceMotion ? nil : .easeOut(duration: 0.2) }

    #if os(iOS)
    private func hapticImpact() {
        // Shared with `RootView`'s tab-switch feedback (2026-09-17) — see `HapticFeedback`.
        HapticFeedback.lightImpact(reduceMotion: reduceMotion)
    }
    #endif

    private var swipeGesture: some Gesture {
        DragGesture(minimumDistance: 16)
            .updating($isDragging) { _, state, _ in state = true }
            .onChanged { value in
                // Vertical drags (scrolling) must not fight this gesture.
                guard abs(value.translation.width) > abs(value.translation.height) else { return }
                // A new live drag always recomputes its stage from the live offset — only the
                // closing settle (after release) needs a frozen value.
                committedTrailingStage = nil
                dragTranslation = value.translation.width
            }
            .onEnded { value in
                let translation = value.translation.width
                // Coordinator (2026-09-17, root-cause fix): the offset reset and the model
                // mutation (`onTogglePaid`/`onToggleActive`) must land in the SAME transaction.
                // Previously `settle()` ran first (animated) and the mutation ran right after,
                // outside that transaction — `line.isPaid`/`isActive` changed instantly while
                // the reveal fill was still 200ms into animating closed, so "the fill finished
                // before the card's own tint caught up." Bundling them here + `.animation(...,
                // value: line.isPaid)` on the card background (see `cardBackground`) makes both
                // interpolate on the same clock, however SwiftData/`@Bindable` propagates the
                // change back into `PeriodView`.
                func commitAndSettle(_ action: @escaping () -> Void) {
                    withAnimation(settleAnimation) {
                        dragTranslation = 0
                        action()
                    }
                    #if os(iOS)
                    hapticImpact()
                    #endif
                }
                // "Bloqueo de líneas pagadas" (2026-09-16): once isPaid == true, swipe-leading
                // (activar/desactivar) is a no-op, and swipe-trailing never advances past the
                // first stage — "Desmarcar pagado" is the only action left, however far the
                // user drags.
                if line.isPaid {
                    if translation <= -swipeCommitThreshold {
                        committedTrailingStage = .paidToggle
                        commitAndSettle(onTogglePaid)
                    } else {
                        withAnimation(settleAnimation) { dragTranslation = 0 }
                    }
                } else if translation >= swipeCommitThreshold {
                    commitAndSettle(onToggleActive)
                } else if translation <= -swipeCommitThreshold {
                    committedTrailingStage = .paidToggle
                    commitAndSettle(onTogglePaid)
                } else {
                    withAnimation(settleAnimation) { dragTranslation = 0 }
                }
            }
    }

    private var displayRow: some View {
        // Coordinator (2026-09-16): the drag-reveal hint must be a full-bleed color fill from
        // the card's own edge to wherever the content has been dragged — not an icon floating
        // over the plain card background. Moved into `cardBackground` (the `.background`
        // modifier below), which — unlike a same-level `ZStack` layer — sizes itself to
        // `rowContent`'s frame AFTER padding, i.e. the actual card bounds, so the fill reaches
        // the real edges instead of sitting 16pt inset from them.
        rowContent
            .offset(x: dragTranslation)
            // DESIGN_LIQUID.md § "Bloques INCOME/EXPENSES": each line is its own card —
            // `AppBackgroundSecondary` (#2A2A2A dark / Frost-equivalent light), 16pt padding,
            // 20pt continuous radius. (Reverted 2026-09-17: briefly tried the "Grande" 24pt
            // density from Developer Tools → Cards, coordinator reverted it back to 16pt.)
            .padding(16)
            .background(cardBackground)
            // Coordinator (2026-09-16): squircle corners were rendering square during an
            // ACTIVE drag (before release), not just around the swipe-reveal strip — a known
            // SwiftUI gotcha where `.clipShape` doesn't reliably re-clip a layer that's still
            // being transformed (`.offset`) every gesture frame unless the content+background
            // is first flattened into a single compositing layer. `.compositingGroup()` forces
            // that flattening so `.clipShape` clips the actual rasterized result every frame,
            // not a stale/partial one.
            .compositingGroup()
            .clipShape(RoundedRectangle(cornerRadius: 20, style: .continuous))
        // "La tarjeta inactiva se atenúa completa" — opacity now dims the whole card
        // (background included), not just the text content.
        .opacity(line.isActive ? 1 : 0.4)
        .animation(reduceMotion ? nil : .easeOut(duration: 0.2), value: line.isActive)
        .gesture(swipeGesture)
        .accessibilityElement(children: .combine)
        .accessibilityValue(accessibilityStateValue)
        .accessibilityActions {
            // Bloqueada: el resto de acciones (Editar, Activar/Desactivar, Eliminar) refleja
            // exactamente lo que el swipe/contextMenu ya no ofrecen cuando isPaid == true —
            // solo queda desmarcar pagado, la única salida del bloqueo.
            Button(line.isPaid ? markUnpaidLabel : markPaidLabel) { onTogglePaid() }
            if !line.isPaid {
                Button(editLabel) { onStartEditing() }
                Button(line.isActive ? deactivateLabel : activateLabel) { onToggleActive() }
                if line.origin == .manual, let onDelete {
                    Button(deleteLabel, role: .destructive) { onDelete() }
                }
            }
        }
        .contextMenu {
            if line.isPaid {
                Button(markUnpaidLabel, systemImage: "checkmark.circle.fill", action: onTogglePaid)
            } else {
                Button(line.isActive ? deactivateLabel : activateLabel, systemImage: line.isActive ? "minus.circle.fill" : "arrow.uturn.backward.circle.fill", action: onToggleActive)
                Button(markPaidLabel, systemImage: "circle", action: onTogglePaid)
                Button(line.currency == .usd
                    ? String(localized: "line_context_menu_switch_to_mxn", defaultValue: "Switch to MXN")
                    : String(localized: "line_context_menu_switch_to_usd", defaultValue: "Switch to USD")
                ) {
                    let newCurrency: Currency = line.currency == .usd ? .mxn : .usd
                    line.currency = newCurrency
                    line.isManuallyEdited = line.origin != .manual ? true : line.isManuallyEdited
                    onQuickCommit()
                    #if os(iOS)
                    UIAccessibility.post(notification: .announcement, argument: String(localized: "line_currency_changed_announcement", defaultValue: "Currency changed to \(newCurrency == .usd ? "USD" : "MXN")"))
                    #endif
                }
                Button(editLabel, systemImage: "pencil", action: onStartEditing)
                if line.origin == .manual, let onDelete {
                    Button(deleteLabel, systemImage: "trash", role: .destructive, action: onDelete)
                        #if os(macOS)
                        .keyboardShortcut(.delete, modifiers: [.command, .shift])
                        #endif
                }
            }
        }
    }

    /// The card's full surface: base Frost, the paid-tint exception, and — on top — the
    /// full-bleed swipe-reveal fill. Lives in `.background` (not a same-level `ZStack` layer)
    /// so it sizes to the card's real bounds (post-padding), not the unpadded content.
    private var cardBackground: some View {
        ZStack {
            // Coordinator (2026-09-21, /update-ui): was `Color("AppBackgroundSecondary")`
            // (#000000 in dark mode — pixel-sampled indistinguishable from the #161617 card
            // behind it). Figma's row background is `Background/AppBackground Tertiary`
            // (#3C3C3C), a real, visible step up from the card.
            if line.isPaid {
                Self.paidRowBackground
            } else {
                Color("AppBackgroundTertiary")
            }
            swipeRevealLayer
        }
        // Coordinator (2026-09-16): the swipe-reveal fill's right edge was showing square
        // corners against the card's continuous-radius squircle. `.clipShape` further up the
        // chain (on `displayRow`) should mask this uniformly, but wasn't in practice — so this
        // applies the exact same shape here too, guaranteeing both share one mask.
        .clipShape(RoundedRectangle(cornerRadius: 20, style: .continuous))
        // Fix 2 (coordinator, 2026-09-17): `isActive`'s opacity dimming already animated
        // (`displayRow`'s `.animation(value: line.isActive)`) — `isPaid`'s tint didn't, so it
        // popped in instantly regardless of what mutated it (this row's own swipe now
        // animates the mutation itself via Fix 1, but any OTHER path that flips `isPaid` —
        // e.g. `.contextMenu`'s "Desmarcar pagado" — still needs this to not just snap).
        .animation(settleAnimation, value: line.isPaid)
    }

    private static let leadingActivateColor = Color.blue
    private static let leadingDeactivateColor = Color.gray

    /// Coordinator (2026-09-16): the outer `.clipShape` on `displayRow`/`cardBackground`
    /// wasn't reliably rounding the reveal fill's outer edge against a live `.offset` — square
    /// corners persisted on real hardware even with `.compositingGroup()`. Each reveal fill now
    /// clips ITSELF: rounded only on the corners that touch the card's real edge, square on the
    /// inner corners that cut against the sliding content — no dependency on an outer mask.
    private static let leadingRevealShape = UnevenRoundedRectangle(
        topLeadingRadius: 20, bottomLeadingRadius: 20, bottomTrailingRadius: 0, topTrailingRadius: 0, style: .continuous
    )
    private static let trailingRevealShape = UnevenRoundedRectangle(
        topLeadingRadius: 0, bottomLeadingRadius: 0, bottomTrailingRadius: 20, topTrailingRadius: 20, style: .continuous
    )

    /// The reveal must be a solid fill from the card's own edge to the drag position — not an
    /// icon floating over gray — with the icon aligned to that outer edge inside the filled
    /// area.
    private var swipeRevealLayer: some View {
        HStack(spacing: 0) {
            if !line.isPaid, dragTranslation > 0 {
                (line.isActive ? Self.leadingDeactivateColor : Self.leadingActivateColor)
                    .frame(width: dragTranslation)
                    .overlay(alignment: .leading) {
                        Label(
                            line.isActive ? deactivateLabel : activateLabel,
                            systemImage: line.isActive ? "minus.circle.fill" : "arrow.uturn.backward.circle.fill"
                        )
                        .labelStyle(.iconOnly)
                        .foregroundStyle(.white)
                        .padding(.leading, 24)
                    }
                    // `.overlay` isn't clipped to its base view's frame by default (the icon
                    // could otherwise peek past the rectangle's own edge at a small drag
                    // width) — and this also rounds the outer (leading) edge against the
                    // card's real corner, square on the inner edge.
                    .clipShape(Self.leadingRevealShape)
                Spacer(minLength: 0)
            } else if dragTranslation < 0 {
                Spacer(minLength: 0)
                // Single-stage trailing swipe now (2026-09-21) — only ever "Marcar"/"Desmarcar
                // pagado", however far the user drags. Editing is press-and-hold →
                // `.contextMenu` only, never a swipe outcome.
                if line.isPaid {
                    // Coordinator (2026-09-21, user's explicit request): once a line is already
                    // paid, this first-stage swipe action is "Desmarcar pagado", not "Marcar
                    // pagado" — red + X, matching the same visual language as the delete stage,
                    // not the green checkmark used to mark something paid in the first place.
                    Self.dangerColor
                        .frame(width: -dragTranslation)
                        .overlay(alignment: .trailing) {
                            Label(markUnpaidLabel, systemImage: "xmark")
                                .labelStyle(.iconOnly)
                                .foregroundStyle(.white)
                                .padding(.trailing, 24)
                        }
                        .clipShape(Self.trailingRevealShape)
                } else {
                    // Coordinator (2026-09-16): dark green — same source hex as the paid-card
                    // tint (`#006338`) — and a flat `checkmark`, not `.circle.fill`.
                    Self.paidHintColor
                        .frame(width: -dragTranslation)
                        .overlay(alignment: .trailing) {
                            Label(markPaidLabel, systemImage: "checkmark")
                                .labelStyle(.iconOnly)
                                .foregroundStyle(.white)
                                .padding(.trailing, 24)
                        }
                        .clipShape(Self.trailingRevealShape)
                }
            }
        }
        // Belt-and-suspenders (coordinator, 2026-09-16): even though the branches above
        // already require `dragTranslation != 0` structurally, an explicit opacity gate makes
        // "fully hidden at rest" independent of animation timing/floating-point edge cases.
        .opacity(dragTranslation == 0 ? 0 : 1)
    }

    private var rowContent: some View {
        HStack(spacing: 10) {
            VStack(alignment: .leading, spacing: 2) {
                Text(line.title)
                    .font(.body)
                    // Coordinator (2026-09-21, /update-ui): paid rows' title text is
                    // `Semantic/Success Green-Dark` (#14332B) against the paid green background,
                    // not the default white/primary.
                    .foregroundStyle(line.isPaid ? Self.paidRowTextColor : .primary)
                if let convertedCaption {
                    Text(convertedCaption)
                        .font(.caption)
                        .foregroundStyle(Color("TextSecondary"))
                        .monospacedDigit()
                }
            }

            Spacer()

            Text(line.amount.currencyString(currency: line.currency))
                // Coordinator (2026-09-21, /update-ui): Figma's amount is Regular weight, not
                // Semibold.
                .font(.body)
                .foregroundStyle(line.isPaid ? Self.paidRowTextColor : .primary)
                .monospacedDigit()
                // Coordinator (2026-09-21, user's explicit request): paid rows now also strike
                // through, not just inactive ones — the green paid tint alone wasn't enough of a
                // "this is done" signal.
                .strikethrough(!line.isActive || line.isPaid)
        }
        // Coordinator (2026-09-16): removed the permanent "palomita discreta" badge — the
        // card's green tint (`cardBackground`, `isPaid`) is now the sole "pagado" indicator at
        // rest; the checkmark only appears transiently in the swipe-reveal hint
        // (`swipeRevealLayer`). VoiceOver is unaffected: `accessibilityStateValue` below
        // already announces "pagada" independent of this icon.
        // Coordinator (2026-09-16): plain tap no longer opens the capture/edit sheet — the
        // only way in is long-press → `.contextMenu` → "Editar" (still wired to
        // `onStartEditing()` there). Swipes (activar/desactivar, pagado, Eliminar) are
        // untouched — this was the row's own tap gesture only.
    }

    /// DESIGN_LIQUID.md: "inactiva" / "pagada" / "inactiva, pagada" / nothing — always in this
    /// order, never conveyed by color/icon alone. `originLabel` now leads the value (the row
    /// dropped its origin icon per the coordinator, so this is the only place that
    /// information still reaches VoiceOver).
    private var accessibilityStateValue: String {
        var parts: [String] = []
        if let originLabel { parts.append(originLabel) }
        if !line.isActive { parts.append(String(localized: "line_a11y_state_inactive", defaultValue: "inactive")) }
        if line.isPaid { parts.append(String(localized: "line_a11y_state_paid", defaultValue: "paid")) }
        return parts.joined(separator: ", ")
    }

}
