import SwiftUI
import SwiftData
import AppleAppLabUI

/// "Inversiones" (PRD feature #12) — reuses `RecurringItem` with `category == .investment`
/// (TRD): a list of contribution accounts with a total at top, each row's "Aportado a la
/// fecha" summing every `isActive` materialized `LineItem` it has generated so far (excludes
/// deactivated lines — same rule as every other total in the app, `CarryOverEngine`).
struct InvestmentsView: View {
    @Environment(\.modelContext) private var context
    @Environment(ExchangeRateStore.self) private var rateStore
    @Query(sort: \RecurringItem.title) private var allItems: [RecurringItem]
    @Query private var allPeriods: [Period]

    @State private var editingItem: RecurringItem?
    @State private var isPresentingNew = false

    private var accounts: [RecurringItem] { allItems.filter { $0.category == .investment } }

    /// Sum of every `isActive` materialized line generated by any investment account, in USD
    /// (mirrors `CarryOverEngine.total`'s currency handling for a simple aggregate view).
    private var totalContributed: Decimal {
        accounts.reduce(Decimal(0)) { $0 + contributedToDate(for: $1) }
    }

    private func contributedToDate(for item: RecurringItem) -> Decimal {
        let lines = allPeriods.flatMap { $0.lineItems ?? [] }.filter { $0.sourceRecurringID == item.id && $0.isActive && $0.isPaid }
        return lines.reduce(Decimal(0)) { partial, line in
            partial + CurrencyConversion.toUSD(amount: line.amount, currency: line.currency, rate: rateStore.currentRate ?? 0)
        }
    }

    var body: some View {
        Group {
            if accounts.isEmpty {
                LabEmptyState(
                    icon: "chart.line.uptrend.xyaxis",
                    title: "Sin inversiones todavía",
                    message: "Registra una cuenta para llevar tus aportaciones recurrentes",
                    config: PatternConfig(accentColor: .accentColor)
                )
            } else {
                List {
                    Section {
                        HStack {
                            Text("Aportado a la fecha")
                            Spacer()
                            Text(totalContributed.currencyString(currency: .usd))
                                .font(.body.weight(.semibold))
                                .monospacedDigit()
                        }
                    }
                    Section {
                        ForEach(accounts) { item in
                            NavigationLink {
                                InvestmentDetailView(item: item)
                            } label: {
                                row(for: item)
                            }
                            .swipeActions {
                                Button(role: .destructive) {
                                    PeriodCoordinator.deleteRecurring(item, context: context, exchangeRate: rateStore.currentRate ?? 0)
                                } label: {
                                    Label("Eliminar", systemImage: "trash")
                                }
                                Button {
                                    editingItem = item
                                } label: {
                                    Label("Editar", systemImage: "pencil")
                                }
                                .tint(.blue)
                            }
                        }
                    }
                }
            }
        }
        .navigationTitle("Inversiones")
        .toolbar {
            ToolbarItem(placement: .primaryAction) {
                Button { isPresentingNew = true } label: { Image(systemName: "plus") }
                    .accessibilityLabel("Agregar cuenta de inversiones")
            }
        }
        .sheet(isPresented: $isPresentingNew) {
            InvestmentEditSheet(item: nil)
        }
        .sheet(item: $editingItem) { item in
            InvestmentEditSheet(item: item)
        }
    }

    private func row(for item: RecurringItem) -> some View {
        HStack(spacing: 12) {
            Image(systemName: "chart.line.uptrend.xyaxis")
                .foregroundStyle(Color.accentColor)
                .frame(width: 28)
                // A11Y #26 (Sarah): purely decorative here — the account name right next to it
                // already says what the row is, the icon adds nothing VoiceOver needs to speak.
                .accessibilityHidden(true)
            VStack(alignment: .leading, spacing: 2) {
                Text(item.accountName?.isEmpty == false ? item.accountName! : item.title)
                    .foregroundStyle(.primary)
                Text("\(item.amount.currencyString(currency: item.currency)) · \(frequencyDescription(item))")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            Spacer()
            VStack(alignment: .trailing, spacing: 2) {
                Text(contributedToDate(for: item).currencyString(currency: .usd))
                    .font(.body.weight(.semibold))
                    .monospacedDigit()
                Text("aportado")
                    .font(.caption2)
                    .foregroundStyle(.secondary)
            }
        }
        .accessibilityElement(children: .combine)
        .accessibilityLabel("\(item.accountName ?? item.title), aportado a la fecha \(contributedToDate(for: item).currencyString(currency: .usd))")
    }

    private func frequencyDescription(_ item: RecurringItem) -> String {
        switch item.frequency {
        case .biweekly: "Cada quincena"
        case .monthlyOnDay(let day): "Día \(day)"
        case .once(let date): "Una vez, \(date.formatted(date: .abbreviated, time: .omitted))"
        }
    }
}

/// One row of the account's full contribution schedule — either backed by a real, materialized
/// `LineItem` (`sourceRecurringID == item.id`) or, when that quincena has never been visited/
/// materialized, purely computed for display (2026-09-21, user's request: the old version only
/// ever listed whatever `Period`s already existed in the store, so an account started years ago
/// showed a handful of rows instead of its whole history through its own end date).
private struct InvestmentScheduleRow {
    let coordinate: PeriodCoordinate
    let amount: Decimal
    let currency: Currency
    let isActive: Bool
    let isPaid: Bool
    let isManuallyEdited: Bool
}

/// Real (materialized) vs. projected — the account's full contribution schedule, computed for
/// every quincena from its own `startDate` through `endDate` (or a year past today if it has
/// none), independent of which quincenas happen to be materialized in the store — same idea as
/// `LoanDetailView`'s `LoanEngine.schedule`, just for a recurring contribution instead of an
/// amortization table. Sorted oldest → newest (user's explicit request).
private struct InvestmentDetailView: View {
    // Coordinator (2026-09-21, user's request): same "hecha" green as `LineItemRow`'s paid
    // rows elsewhere in the app — same source hex, not a separate color for this screen.
    private static let paidRowBackground = Color(red: 0x00 / 255.0, green: 0x63 / 255.0, blue: 0x38 / 255.0)
    private static let paidRowTextColor = Color(red: 0x14 / 255.0, green: 0x33 / 255.0, blue: 0x2B / 255.0)

    let item: RecurringItem
    @Environment(\.modelContext) private var context
    @Query private var allPeriods: [Period]
    @Query(sort: \RecurringItem.title) private var allRecurringItems: [RecurringItem]
    @Query(sort: \Subscription.name) private var allSubscriptions: [Subscription]
    @Environment(ExchangeRateStore.self) private var rateStore
    // Coordinator (2026-09-17): "Editar" in the detail toolbar — same placement/pattern as
    // `LoanDetailView`/`CreditCardDetailView`, reuses `InvestmentEditSheet` (same form
    // `InvestmentsView` uses for "Nueva cuenta"/its own "Editar" swipe action).
    @State private var isPresentingEdit = false
    @State private var isPresentingPastPaymentsConfirm = false

    private var effectiveRate: Decimal { rateStore.currentRate ?? 0 }

    private var recurringSnapshot: RecurringItemSnapshot {
        RecurringItemSnapshot(id: item.id, kind: item.kind, title: item.title, amount: item.amount, currency: item.currency, frequency: item.frequency, startDate: item.civilStartDate, endDate: item.civilEndDate, isActive: item.isActive, category: item.category)
    }

    private var recurringSnapshots: [RecurringItemSnapshot] {
        allRecurringItems.map {
            RecurringItemSnapshot(id: $0.id, kind: $0.kind, title: $0.title, amount: $0.amount, currency: $0.currency, frequency: $0.frequency, startDate: $0.civilStartDate, endDate: $0.civilEndDate, isActive: $0.isActive, category: $0.category)
        }
    }

    private var subscriptionSnapshots: [SubscriptionSnapshot] {
        allSubscriptions.map {
            SubscriptionSnapshot(id: $0.id, name: $0.name, price: $0.price, currency: $0.currency, paymentDay: $0.paymentDay, startDate: $0.civilStartDate, endDate: $0.civilEndDate, kind: $0.kind, isActive: $0.isActive, isBiweekly: $0.isBiweekly)
        }
    }

    private var todayCoordinate: PeriodCoordinate { PeriodDateEngine.coordinate(containing: CivilDate.today()) }

    /// No end date on the account → project a year (24 quincenas) past whichever is later,
    /// today or the account's own start, instead of an unbounded list.
    private var horizonCoordinate: PeriodCoordinate {
        if let end = item.civilEndDate { return PeriodDateEngine.coordinate(containing: end) }
        var coordinate = max(todayCoordinate, PeriodDateEngine.coordinate(containing: item.civilStartDate))
        for _ in 0..<24 { coordinate = coordinate.next }
        return coordinate
    }

    private func materializedLine(for coordinate: PeriodCoordinate) -> LineItem? {
        guard let period = allPeriods.first(where: { $0.coordinate == coordinate }) else { return nil }
        return (period.lineItems ?? []).first(where: { $0.sourceRecurringID == item.id })
    }

    private var scheduleRows: [InvestmentScheduleRow] {
        ProjectionEngine.occurrenceCoordinates(for: recurringSnapshot, through: horizonCoordinate)
            .map { coordinate in
                if let line = materializedLine(for: coordinate) {
                    return InvestmentScheduleRow(coordinate: coordinate, amount: line.amount, currency: line.currency, isActive: line.isActive, isPaid: line.isPaid, isManuallyEdited: line.isManuallyEdited)
                }
                let generated = ProjectionEngine.generateRecurringLines(for: coordinate, recurringItems: [recurringSnapshot]).first
                return InvestmentScheduleRow(coordinate: coordinate, amount: generated?.amount ?? item.amount, currency: generated?.currency ?? item.currency, isActive: true, isPaid: false, isManuallyEdited: false)
            }
            .sorted { $0.coordinate < $1.coordinate }
    }

    private var contributedToDate: Decimal {
        scheduleRows.filter { $0.isActive && $0.isPaid }.reduce(Decimal(0)) { partial, row in
            partial + CurrencyConversion.toUSD(amount: row.amount, currency: row.currency, rate: effectiveRate)
        }
    }

    /// Coordinator (2026-09-21, user's request — "hay que preguntar si se han hecho todos los
    /// pagos"): an account started well before today has real-world contributions this app
    /// never recorded. Offered once (`item.pastPaymentsReviewed` gates it for good, whichever
    /// way the user answers) whenever there's at least one past, unpaid row to ask about.
    private var unconfirmedPastRows: [InvestmentScheduleRow] {
        scheduleRows.filter { $0.coordinate <= todayCoordinate && !$0.isPaid }
    }

    private var shouldOfferPastPaymentsReview: Bool {
        !item.pastPaymentsReviewed && item.civilStartDate < CivilDate.today() && !unconfirmedPastRows.isEmpty
    }

    /// Builds a plain `String` (never interpolated straight into `Text(_:)`, which would treat
    /// it as `LocalizedStringKey` and add locale thousands-grouping to the year, e.g. "2,027")
    /// so `Text(verbatim:)` can render it untouched: "Sep 1–15, 2026".
    private func periodLabel(for coordinate: PeriodCoordinate) -> String {
        let monthName = Calendar.current.shortMonthSymbols[coordinate.month - 1]
        let dayRange = coordinate.half == .first ? "1–15" : "16–fin"
        return "\(monthName) \(dayRange), \(coordinate.year)"
    }

    private func stateLabel(for row: InvestmentScheduleRow) -> String {
        if !row.isActive { return "Desactivada" }
        if row.isPaid { return "Hecha" }
        if row.isManuallyEdited { return "Editada" }
        return "Proyectada"
    }

    /// Materializes `coordinate` if needed — via `forceMaterialize`, not `materializeIfNeeded`,
    /// since a row here can predate whatever the user has already browsed to in Quincena
    /// (`materializeIfNeeded` would silently clamp that to the existing anchor instead of
    /// creating the real period) — and toggles this account's own line's `isPaid`, same
    /// semantics as `LineItemRow`'s swipe-trailing "marcar pagado".
    private func togglePaid(for coordinate: PeriodCoordinate) {
        let period = PeriodCoordinator.forceMaterialize(coordinate: coordinate, context: context, recurringItems: recurringSnapshots, subscriptions: subscriptionSnapshots, exchangeRate: effectiveRate)
        guard let line = (period.lineItems ?? []).first(where: { $0.sourceRecurringID == item.id }) else { return }
        line.isPaid.toggle()
        line.paidAt = line.isPaid ? CivilDate.today() : nil
        line.isManuallyEdited = true
        try? context.save()
        PeriodCoordinator.recomputeForward(after: period, context: context, exchangeRate: effectiveRate)
        try? context.save()
    }

    private func markPastRowsAsPaid() {
        let rows = unconfirmedPastRows
        guard let earliestCoordinate = rows.map(\.coordinate).min() else { return }
        // Ascending order (oldest → newest, same as `rows` itself) so each new period's own
        // carry-over lookup finds its already-created predecessor — see `forceMaterialize`'s
        // doc comment.
        for row in rows {
            let period = PeriodCoordinator.forceMaterialize(coordinate: row.coordinate, context: context, recurringItems: recurringSnapshots, subscriptions: subscriptionSnapshots, exchangeRate: effectiveRate)
            guard let line = (period.lineItems ?? []).first(where: { $0.sourceRecurringID == item.id }) else { continue }
            line.isPaid = true
            line.paidAt = CivilDate.today()
            line.isManuallyEdited = true
        }
        item.pastPaymentsReviewed = true
        try? context.save()
        if let earliestPeriod = PeriodCoordinator.fetchPeriod(coordinate: earliestCoordinate, context: context) {
            PeriodCoordinator.recomputeForward(after: earliestPeriod, context: context, exchangeRate: effectiveRate)
            try? context.save()
        }
    }

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 20) {
                VStack(alignment: .leading, spacing: 8) {
                    Text("APORTADO A LA FECHA")
                        .font(.caption2)
                        .tracking(1.2)
                        .foregroundStyle(.secondary)
                    Text(contributedToDate.currencyString(currency: .usd))
                        .font(.largeTitle.weight(.bold))
                        .monospacedDigit()
                        .foregroundStyle(Color.accentColor)
                }
                .padding(16)
                .background(RoundedRectangle(cornerRadius: 20, style: .continuous).fill(.ultraThinMaterial.opacity(0.5)))

                LazyVStack(spacing: 0) {
                    ForEach(scheduleRows, id: \.coordinate) { row in
                        Button {
                            togglePaid(for: row.coordinate)
                        } label: {
                            HStack {
                                VStack(alignment: .leading, spacing: 2) {
                                    Text(verbatim: periodLabel(for: row.coordinate))
                                        .font(.body)
                                        .foregroundStyle(row.isPaid ? Self.paidRowTextColor : .primary)
                                    Text(stateLabel(for: row))
                                        .font(.caption)
                                        .foregroundStyle(row.isPaid ? Self.paidRowTextColor : .secondary)
                                }
                                Spacer()
                                Text(row.amount.currencyString(currency: row.currency))
                                    .monospacedDigit()
                                    .foregroundStyle(row.isPaid ? Self.paidRowTextColor : .primary)
                                    .strikethrough(!row.isActive || row.isPaid)
                            }
                            .padding(.horizontal, 12)
                            .padding(.vertical, 8)
                            .background(row.isPaid ? Self.paidRowBackground : .clear)
                            .clipShape(RoundedRectangle(cornerRadius: 12, style: .continuous))
                            .contentShape(Rectangle())
                        }
                        .buttonStyle(.plain)
                        .accessibilityElement(children: .combine)
                        // A11Y #27 (Sarah): `.combine` alone only concatenates the child texts
                        // in visual order — an explicit `.accessibilityValue` makes the state
                        // unambiguous regardless of layout order.
                        .accessibilityValue(stateLabel(for: row))
                        .accessibilityHint(row.isPaid ? "Doble toque para desmarcar como hecha" : "Doble toque para marcar como hecha")
                        if row.coordinate != scheduleRows.last?.coordinate { Divider() }
                    }
                }
                .padding(16)
                .background(RoundedRectangle(cornerRadius: 20, style: .continuous).fill(.ultraThinMaterial.opacity(0.5)))
            }
            .padding(16)
        }
        .navigationTitle(item.accountName ?? item.title)
        #if os(iOS)
        .navigationBarTitleDisplayMode(.inline)
        #endif
        .toolbar {
            ToolbarItem(placement: .primaryAction) {
                Button("Editar") { isPresentingEdit = true }
            }
        }
        .sheet(isPresented: $isPresentingEdit) {
            InvestmentEditSheet(item: item)
        }
        .onAppear {
            if shouldOfferPastPaymentsReview { isPresentingPastPaymentsConfirm = true }
        }
        .confirmationDialog(
            "¿Ya hiciste las \(unconfirmedPastRows.count) aportaciones anteriores, desde \(unconfirmedPastRows.first.map { periodLabel(for: $0.coordinate) } ?? "")?",
            isPresented: $isPresentingPastPaymentsConfirm,
            titleVisibility: .visible
        ) {
            Button("Sí, márcalas como hechas") { markPastRowsAsPaid() }
            Button("No, están pendientes") {
                item.pastPaymentsReviewed = true
                try? context.save()
            }
            Button("Preguntar después", role: .cancel) {}
        }
    }
}

private enum InvestmentFrequencyKind: String, CaseIterable, Identifiable {
    case biweekly = "Cada quincena"
    case monthlyOnDay = "Mensual"
    var id: String { rawValue }
}

private struct InvestmentEditSheet: View {
    @Environment(\.modelContext) private var context
    @Environment(ExchangeRateStore.self) private var rateStore
    @Environment(\.dismiss) private var dismiss

    let item: RecurringItem?

    @State private var accountName: String
    @State private var amount: Decimal
    @State private var currency: Currency
    @State private var frequencyKind: InvestmentFrequencyKind
    @State private var startDate: Date
    @State private var hasEndDate: Bool
    @State private var endDate: Date
    @State private var isActive: Bool

    init(item: RecurringItem?) {
        self.item = item
        _accountName = State(initialValue: item?.accountName ?? item?.title ?? "")
        _amount = State(initialValue: item?.amount ?? 0)
        _currency = State(initialValue: item?.currency ?? .usd)
        _startDate = State(initialValue: item?.startDate ?? .now)
        _hasEndDate = State(initialValue: item?.endDate != nil)
        _endDate = State(initialValue: item?.endDate ?? .now)
        _isActive = State(initialValue: item?.isActive ?? true)

        switch item?.frequency ?? .biweekly {
        case .monthlyOnDay:
            _frequencyKind = State(initialValue: .monthlyOnDay)
        default:
            _frequencyKind = State(initialValue: .biweekly)
        }
    }

    private var isFormValid: Bool {
        !accountName.isEmpty && ValidationRange.amount.contains(amount)
    }

    private var resolvedFrequency: RecurringFrequency {
        switch frequencyKind {
        case .biweekly: .biweekly
        // El día de aportación mensual se deriva del día del mes de "Inicio" (feedback del usuario).
        case .monthlyOnDay: .monthlyOnDay(Calendar.current.component(.day, from: startDate))
        }
    }

    var body: some View {
        NavigationStack {
            Form {
                Section {
                    LabTextField(placeholder: "Cuenta (GBM, Cetesdirecto…)", text: $accountName, config: PatternConfig(accentColor: .accentColor))
                    HStack {
                        // Coordinator (2026-09-17): `LabDecimalField` — centralized fix for
                        // "0.00 isn't a placeholder, has to be deleted by hand".
                        LabDecimalField(placeholder: "$100", value: $amount)
                        Picker("Moneda", selection: $currency) {
                            Text("USD").tag(Currency.usd)
                            Text("MXN").tag(Currency.mxn)
                        }
                        .pickerStyle(.segmented)
                        .frame(width: 140)
                    }
                }

                Section("Frecuencia") {
                    Picker("Frecuencia", selection: $frequencyKind) {
                        ForEach(InvestmentFrequencyKind.allCases) { Text($0.rawValue).tag($0) }
                    }
                }

                Section {
                    // El día de aportación mensual se deriva del día del mes de "Inicio" — no
                    // hay un campo separado que pueda desincronizarse (feedback del usuario).
                    DatePicker("Inicio", selection: $startDate, displayedComponents: .date)
                    Toggle("Tiene fecha de fin", isOn: $hasEndDate)
                    if hasEndDate {
                        DatePicker("Fin", selection: $endDate, displayedComponents: .date)
                    }
                    Toggle("Activa", isOn: $isActive)
                }
            }
            .navigationTitle(item == nil ? "Nueva cuenta" : "Editar cuenta")
            #if os(iOS)
            .navigationBarTitleDisplayMode(.inline)
            #endif
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancelar") { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Guardar") { save() }.disabled(!isFormValid)
                }
            }
        }
    }

    private func save() {
        let resolvedEndDate = hasEndDate ? endDate : nil
        let target: RecurringItem
        if let item {
            item.title = accountName
            item.accountName = accountName
            item.amount = amount
            item.currency = currency
            item.frequency = resolvedFrequency
            item.civilStartDate = CivilDate(from: startDate, calendar: .current)
            item.civilEndDate = resolvedEndDate.map { CivilDate(from: $0, calendar: .current) }
            item.isActive = isActive
            target = item
        } else {
            // An "aportación" is money leaving day-to-day cash flow into the investment
            // account — treated as an EXPENSE for TOTAL EXPENSES/sobrante, same as any other
            // recurring outflow (TRD does not carve investments out of the normal kind-based
            // total math, only out of the "Ingresos/Gastos recurrentes" lists' UI).
            let newItem = RecurringItem(
                kind: .expense, title: accountName, amount: amount, currency: currency, frequency: resolvedFrequency,
                startDate: startDate, endDate: resolvedEndDate, isActive: isActive, category: .investment, accountName: accountName
            )
            context.insert(newItem)
            target = newItem
        }
        try? context.save()
        PeriodCoordinator.reprojectRecurring(item: target, context: context, exchangeRate: rateStore.currentRate ?? 0)
        dismiss()
    }
}
