import SwiftUI
import SwiftData
import AppleAppLabUI

/// "Inversiones" (PRD feature #12) — reuses `RecurringItem` with `category == .investment`
/// (TRD): a list of contribution accounts with a total at top, each row's "Aportado a la
/// fecha" summing every `isActive` materialized `LineItem` it has generated so far (excludes
/// deactivated lines — same rule as every other total in the app, `CarryOverEngine`).
struct InvestmentsView: View {
    @Environment(\.modelContext) private var context
    @Environment(ExchangeRateStore.self) private var rateStore
    @Query(sort: \RecurringItem.title) private var allItems: [RecurringItem]
    @Query private var allPeriods: [Period]

    @State private var editingItem: RecurringItem?
    @State private var isPresentingNew = false

    private var accounts: [RecurringItem] { allItems.filter { $0.category == .investment } }

    /// Sum of every `isActive` materialized line generated by any investment account, in USD
    /// (mirrors `CarryOverEngine.total`'s currency handling for a simple aggregate view).
    private var totalContributed: Decimal {
        accounts.reduce(Decimal(0)) { $0 + contributedToDate(for: $1) }
    }

    private func contributedToDate(for item: RecurringItem) -> Decimal {
        let lines = allPeriods.flatMap { $0.lineItems ?? [] }.filter { $0.sourceRecurringID == item.id && $0.isActive && $0.isPaid }
        return lines.reduce(Decimal(0)) { partial, line in
            partial + CurrencyConversion.toUSD(amount: line.amount, currency: line.currency, rate: rateStore.currentRate ?? 0)
        }
    }

    var body: some View {
        Group {
            if accounts.isEmpty {
                LabEmptyState(
                    icon: "chart.line.uptrend.xyaxis",
                    title: "Sin inversiones todavía",
                    message: "Registra una cuenta para llevar tus aportaciones recurrentes",
                    config: PatternConfig(accentColor: .accentColor)
                )
            } else {
                List {
                    Section {
                        HStack {
                            Text("Aportado a la fecha")
                            Spacer()
                            Text(totalContributed.currencyString(currency: .usd))
                                .font(.body.weight(.semibold))
                                .monospacedDigit()
                        }
                    }
                    Section {
                        ForEach(accounts) { item in
                            NavigationLink {
                                InvestmentDetailView(item: item)
                            } label: {
                                row(for: item)
                            }
                            .swipeActions {
                                Button(role: .destructive) {
                                    PeriodCoordinator.deleteRecurring(item, context: context, exchangeRate: rateStore.currentRate ?? 0)
                                } label: {
                                    Label("Eliminar", systemImage: "trash")
                                }
                                Button {
                                    editingItem = item
                                } label: {
                                    Label("Editar", systemImage: "pencil")
                                }
                                .tint(.blue)
                            }
                        }
                    }
                }
            }
        }
        .navigationTitle("Inversiones")
        .toolbar {
            ToolbarItem(placement: .primaryAction) {
                Button { isPresentingNew = true } label: { Image(systemName: "plus") }
                    .accessibilityLabel("Agregar cuenta de inversiones")
            }
        }
        .sheet(isPresented: $isPresentingNew) {
            InvestmentEditSheet(item: nil)
        }
        .sheet(item: $editingItem) { item in
            InvestmentEditSheet(item: item)
        }
    }

    private func row(for item: RecurringItem) -> some View {
        HStack(spacing: 12) {
            Image(systemName: "chart.line.uptrend.xyaxis")
                .foregroundStyle(Color.accentColor)
                .frame(width: 28)
                // A11Y #26 (Sarah): purely decorative here — the account name right next to it
                // already says what the row is, the icon adds nothing VoiceOver needs to speak.
                .accessibilityHidden(true)
            VStack(alignment: .leading, spacing: 2) {
                Text(item.accountName?.isEmpty == false ? item.accountName! : item.title)
                    .foregroundStyle(.primary)
                Text("\(item.amount.currencyString(currency: item.currency)) · \(frequencyDescription(item))")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            Spacer()
            VStack(alignment: .trailing, spacing: 2) {
                Text(contributedToDate(for: item).currencyString(currency: .usd))
                    .font(.body.weight(.semibold))
                    .monospacedDigit()
                Text("aportado")
                    .font(.caption2)
                    .foregroundStyle(.secondary)
            }
        }
        .accessibilityElement(children: .combine)
        .accessibilityLabel("\(item.accountName ?? item.title), aportado a la fecha \(contributedToDate(for: item).currencyString(currency: .usd))")
    }

    private func frequencyDescription(_ item: RecurringItem) -> String {
        switch item.frequency {
        case .biweekly: "Cada quincena"
        case .monthlyOnDay(let day): "Día \(day)"
        case .once(let date): "Una vez, \(date.formatted(date: .abbreviated, time: .omitted))"
        }
    }
}

/// Real (materialized, not manually-zeroed) vs. projected — the account's simple "history".
/// `.investment` lines are never balance-tracked like a `Loan` (no principal/interest), so
/// this just lists what's been materialized so far, most recent first.
private struct InvestmentDetailView: View {
    let item: RecurringItem
    @Query private var allPeriods: [Period]
    @Environment(ExchangeRateStore.self) private var rateStore
    // Coordinator (2026-09-17): "Editar" in the detail toolbar — same placement/pattern as
    // `LoanDetailView`/`CreditCardDetailView`, reuses `InvestmentEditSheet` (same form
    // `InvestmentsView` uses for "Nueva cuenta"/its own "Editar" swipe action).
    @State private var isPresentingEdit = false

    private var lines: [(period: Period, line: LineItem)] {
        allPeriods
            .sorted { $0.coordinate > $1.coordinate }
            .compactMap { period in
                guard let line = (period.lineItems ?? []).first(where: { $0.sourceRecurringID == item.id }) else { return nil }
                return (period, line)
            }
    }

    private var contributedToDate: Decimal {
        lines.filter { $0.line.isActive && $0.line.isPaid }.reduce(Decimal(0)) { partial, entry in
            partial + CurrencyConversion.toUSD(amount: entry.line.amount, currency: entry.line.currency, rate: rateStore.currentRate ?? 0)
        }
    }

    /// Builds a plain `String` (never interpolated straight into `Text(_:)`, which would treat
    /// it as `LocalizedStringKey` and add locale thousands-grouping to the year, e.g. "2,027")
    /// so `Text(verbatim:)` can render it untouched: "Sep 1–15, 2026".
    private func periodLabel(for coordinate: PeriodCoordinate) -> String {
        let monthName = Calendar.current.shortMonthSymbols[coordinate.month - 1]
        let dayRange = coordinate.half == .first ? "1–15" : "16–fin"
        return "\(monthName) \(dayRange), \(coordinate.year)"
    }

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 20) {
                VStack(alignment: .leading, spacing: 8) {
                    Text("APORTADO A LA FECHA")
                        .font(.caption2)
                        .tracking(1.2)
                        .foregroundStyle(.secondary)
                    Text(contributedToDate.currencyString(currency: .usd))
                        .font(.largeTitle.weight(.bold))
                        .monospacedDigit()
                        .foregroundStyle(Color.accentColor)
                }
                .padding(16)
                .background(RoundedRectangle(cornerRadius: 20, style: .continuous).fill(.ultraThinMaterial.opacity(0.5)))

                LazyVStack(spacing: 0) {
                    ForEach(lines, id: \.line.id) { entry in
                        HStack {
                            VStack(alignment: .leading, spacing: 2) {
                                Text(verbatim: periodLabel(for: entry.period.coordinate))
                                    .font(.body)
                                if !entry.line.isActive {
                                    Text("Desactivada").font(.caption).foregroundStyle(.secondary)
                                } else if entry.line.isManuallyEdited {
                                    Text("Editada").font(.caption).foregroundStyle(.secondary)
                                } else {
                                    Text("Proyectada").font(.caption).foregroundStyle(.secondary)
                                }
                            }
                            Spacer()
                            Text(entry.line.amount.currencyString(currency: entry.line.currency))
                                .monospacedDigit()
                                .strikethrough(!entry.line.isActive)
                        }
                        .padding(.vertical, 8)
                        .accessibilityElement(children: .combine)
                        // A11Y #27 (Sarah): `.combine` alone only concatenates the child texts
                        // in visual order — an explicit `.accessibilityValue` makes the state
                        // ("desactivada"/"editada"/"proyectada") unambiguous regardless of
                        // layout order.
                        .accessibilityValue(entry.line.isActive ? (entry.line.isManuallyEdited ? "editada" : "proyectada") : "desactivada")
                        if entry.line.id != lines.last?.line.id { Divider() }
                    }
                }
                .padding(16)
                .background(RoundedRectangle(cornerRadius: 20, style: .continuous).fill(.ultraThinMaterial.opacity(0.5)))
            }
            .padding(16)
        }
        .navigationTitle(item.accountName ?? item.title)
        #if os(iOS)
        .navigationBarTitleDisplayMode(.inline)
        #endif
        .toolbar {
            ToolbarItem(placement: .primaryAction) {
                Button("Editar") { isPresentingEdit = true }
            }
        }
        .sheet(isPresented: $isPresentingEdit) {
            InvestmentEditSheet(item: item)
        }
    }
}

private enum InvestmentFrequencyKind: String, CaseIterable, Identifiable {
    case biweekly = "Cada quincena"
    case monthlyOnDay = "Mensual"
    var id: String { rawValue }
}

private struct InvestmentEditSheet: View {
    @Environment(\.modelContext) private var context
    @Environment(ExchangeRateStore.self) private var rateStore
    @Environment(\.dismiss) private var dismiss

    let item: RecurringItem?

    @State private var accountName: String
    @State private var amount: Decimal
    @State private var currency: Currency
    @State private var frequencyKind: InvestmentFrequencyKind
    @State private var startDate: Date
    @State private var hasEndDate: Bool
    @State private var endDate: Date
    @State private var isActive: Bool

    init(item: RecurringItem?) {
        self.item = item
        _accountName = State(initialValue: item?.accountName ?? item?.title ?? "")
        _amount = State(initialValue: item?.amount ?? 0)
        _currency = State(initialValue: item?.currency ?? .usd)
        _startDate = State(initialValue: item?.startDate ?? .now)
        _hasEndDate = State(initialValue: item?.endDate != nil)
        _endDate = State(initialValue: item?.endDate ?? .now)
        _isActive = State(initialValue: item?.isActive ?? true)

        switch item?.frequency ?? .biweekly {
        case .monthlyOnDay:
            _frequencyKind = State(initialValue: .monthlyOnDay)
        default:
            _frequencyKind = State(initialValue: .biweekly)
        }
    }

    private var isFormValid: Bool {
        !accountName.isEmpty && ValidationRange.amount.contains(amount)
    }

    private var resolvedFrequency: RecurringFrequency {
        switch frequencyKind {
        case .biweekly: .biweekly
        // El día de aportación mensual se deriva del día del mes de "Inicio" (feedback del usuario).
        case .monthlyOnDay: .monthlyOnDay(Calendar.current.component(.day, from: startDate))
        }
    }

    var body: some View {
        NavigationStack {
            Form {
                Section {
                    LabTextField(placeholder: "Cuenta (GBM, Cetesdirecto…)", text: $accountName, config: PatternConfig(accentColor: .accentColor))
                    HStack {
                        // Coordinator (2026-09-17): `LabDecimalField` — centralized fix for
                        // "0.00 isn't a placeholder, has to be deleted by hand".
                        LabDecimalField(placeholder: "Aportación", value: $amount)
                        Picker("Moneda", selection: $currency) {
                            Text("USD").tag(Currency.usd)
                            Text("MXN").tag(Currency.mxn)
                        }
                        .pickerStyle(.segmented)
                        .frame(width: 140)
                    }
                }

                Section("Frecuencia") {
                    Picker("Frecuencia", selection: $frequencyKind) {
                        ForEach(InvestmentFrequencyKind.allCases) { Text($0.rawValue).tag($0) }
                    }
                }

                Section {
                    // El día de aportación mensual se deriva del día del mes de "Inicio" — no
                    // hay un campo separado que pueda desincronizarse (feedback del usuario).
                    DatePicker("Inicio", selection: $startDate, displayedComponents: .date)
                    Toggle("Tiene fecha de fin", isOn: $hasEndDate)
                    if hasEndDate {
                        DatePicker("Fin", selection: $endDate, displayedComponents: .date)
                    }
                    Toggle("Activa", isOn: $isActive)
                }
            }
            .navigationTitle(item == nil ? "Nueva cuenta" : "Editar cuenta")
            #if os(iOS)
            .navigationBarTitleDisplayMode(.inline)
            #endif
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancelar") { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Guardar") { save() }.disabled(!isFormValid)
                }
            }
        }
    }

    private func save() {
        let resolvedEndDate = hasEndDate ? endDate : nil
        let target: RecurringItem
        if let item {
            item.title = accountName
            item.accountName = accountName
            item.amount = amount
            item.currency = currency
            item.frequency = resolvedFrequency
            item.civilStartDate = CivilDate(from: startDate, calendar: .current)
            item.civilEndDate = resolvedEndDate.map { CivilDate(from: $0, calendar: .current) }
            item.isActive = isActive
            target = item
        } else {
            // An "aportación" is money leaving day-to-day cash flow into the investment
            // account — treated as an EXPENSE for TOTAL EXPENSES/sobrante, same as any other
            // recurring outflow (TRD does not carve investments out of the normal kind-based
            // total math, only out of the "Ingresos/Gastos recurrentes" lists' UI).
            let newItem = RecurringItem(
                kind: .expense, title: accountName, amount: amount, currency: currency, frequency: resolvedFrequency,
                startDate: startDate, endDate: resolvedEndDate, isActive: isActive, category: .investment, accountName: accountName
            )
            context.insert(newItem)
            target = newItem
        }
        try? context.save()
        PeriodCoordinator.reprojectRecurring(item: target, context: context, exchangeRate: rateStore.currentRate ?? 0)
        dismiss()
    }
}
